### ISSUE TITLE
async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by LukaszP2** [Mr-Groch/HA-ESA-NASK-Air-Quality#1]
Hi!

Great job!

I got an error so I report ;)

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for esa_nask using this method at custom_components/esa_nask/__init__.py, line 23: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by Mr-Groch** [comment]
Thanks for reporting! Fixed in 1.0.0
