### ISSUE TITLE
Air rating/Ocena powietrza

### ISSUE THREAD

**Issue by GSzabados** [Mr-Groch/HA-ESA-NASK-Air-Quality#2]
**Is your feature request related to a problem? Please describe.**
The station provides a text description of air quality (rating) as well, like today "Bardzo Dobry".

I haven't looked at the API that does it have the same or the values are interpreted only by the ranges. Would be possible to add that as well as a sensor, like the GIOS integration does?

**Describe the solution you'd like**
Have a sensor which contains the rating text.

**Describe alternatives you've considered**
Create an Automation manually with a select.

**Additional context**
Example from GIOS

![20230315_153307](https://user-images.githubusercontent.com/35445496/225342145-0fdece63-ee0c-44c2-8472-5282d5fc7f26.jpg)

Otherwise great work! I just looked at the sensor today that has it got any API, and here it is a super working integration! Thanks!

**Comment by Mr-Groch** [comment]
Hi, there isn't any air rating description in ESA NASK API unfortunately. But there is reference to icon to show in pm2.5 sensor - I can set that icon id string as an attribute in pm2.5 sensor - it will be OK for you? I can also try to localize it

Here you can see example API response from ESA NASK:
```json
{
	"id": 2010,
	"province": "ŚLĄSKIE",
	"city": "KNURÓW",
	"street": "UL. FELIKSA MICHALSKIEGO",
	"streetNo": "27",
	"apartment": null,
	"postCode": "44-193",
	"name": "MIEJSKA SZKOŁA PODSTAWOWA NR 3 W KNUROWIE",
	"shortName": "MSP 3 KNURÓW",
	"latitude": "50.2109434",
	"longitude": "18.6452996",
	"ios": false,
	"eduOnly": false,
	"project": "kprm",
	"sensors": [{
		"name": "publoco",
		"placement": "OUTSIDE",
		"logo": null,
		"lastMeasurement": {
			"pm25": {
				"value": 6.958823529411765,
				"icon": "veryGood",
				"color": "299d3d"
			},
			"pm10": {
				"value": 8.311764705882354,
				"icon": null,
				"color": null
			},
			"humidity": 57.54705882352942,
			"pressure": 996.6235294117648,
			"temperature": 4.911764705882353,
			"dewPoint": 12.141176470588235
		}
	}]
}
```

**Comment by GSzabados** [comment]
> I can set that icon id string as an attribute in pm2.5 sensor

Thanks! That would be great!

**Comment by Mr-Groch** [comment]
Added as described. Translation was not possible currently (HA provides translation of state attributes only for climate devices currently)

**Comment by GSzabados** [comment]
> Translation was not possible currently

No worries. As an attribute is good enough for me. Thanks!
